spring.application.name=carritodecompras
server.port=8085
# Base de datos propia para este servicio
spring.datasource.url=jdbc:mysql://localhost:3306/db_carrito?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true