spring.application.name=service__catalogo__producto
server.port=8082
#Conexion a DB Pacientes
spring.datasource.url=jdbc:mysql://localhost:3306/db_catalogo_producto?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true